# Generated by Django 6.0.2 on 2026-03-05 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_area_department_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.officer'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complaints.department'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.area'),
        ),
    ]
