# Generated by Django 6.0.2 on 2026-03-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_complaint_assigned_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaints/'),
        ),
    ]
