# Generated by Django 6.0.2 on 2026-03-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_complaint_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
