# Generated by Django 6.0.2 on 2026-03-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_complaint_lat_complaint_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
